#!/bin/bash

# Core session utilities (session slice)
uwsm app -s s -- "$HOME"/.config/hypr/scripts/portal &
uwsm app -s s -- wl-paste --watch cliphist store &

# Background services (background slice)
uwsm app -s b -- udiskie &
uwsm app -s b -- easyeffects --gapplication-service &
uwsm app -s b -- swayosd-server &

# UI applications (app slice - default)
uwsm app -- pypr --debug /tmp/pypr.log &
uwsm app -- waybar &
uwsm app -- swaync &
