#!/bin/bash

if [ -z "$1" ]; then
  exit 1
fi

program="$1"
shift

if ! command -v "$program" >/dev/null 2>&1; then
  notify-send "Program not found" "Make sure you have installed $program"
  exit 1
else
  # Check if we're in a uwsm session
  if command -v uwsm >dev/null 2>&1 && uwsm check; then
    exec uwsm app -- "$program" "$@"
  else
    exec "$program" "$@"
  fi
fi
