[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.volume]
command = "pavucontrol"
unfocus = "hide"
position = "1% 8%"
lazy = true
force_monitor = "eDP-1"

[scratchpads.terminal]
command = "foot -a scratchpad-large"
lazy = true

[scratchpads.yazi]
command = "foot -a scratchpad-large fish -c yazi"
unfocus = "hide"
hysteresis = 0.1
lazy = true

[scratchpads.btop]
command = "foot -a scratchpad-large btop"
lazy = true

[scratchpads.nvtop]
command = "foot -a scratchpad-large nvtop"
lazy = true

[scratchpads.topgrade-system]
command = "foot -a scratchpad-large zsh -c 'up'"
lazy = true

[scratchpads.topgrade-all]
command = "foot -a scratchpad-large zsh -c 'upall'"
lazy = true

[scratchpads.bluetooth]
command = "overskride"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.wifi]
command = "iwgtk"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.network]
command = "nm-connection-editor"
animation = "fromRight"
margin = 20
lazy = true
